# Generated by Django 6.0.5 on 2026-08-29 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stored_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='messager_email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='messager_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='messager_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='abhisheksingh913396@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Abhishek Kumar Singh', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
